spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  config:
    import: optional:configserver:http://localhost:8071/
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      env:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  info:
    app:
      name: "cards"
      description: "Jane Bank Cards Application"
      version: "1.0.0"
  logging:
    level:
      com:
        jane:
          cards: DEBUG