services:
  accounts:
    image: ritujane78/accounts:1
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - janeBank
  loans:
    image: ritujane78/loans:1
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - janeBank
  cards:
    image: ritujane78/cards:1
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - janeBank
networks:
  janeBank:
    driver: "bridge"