spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://configserver:8071/ # use localhost instead of serverserver when running locally
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  cloud:
   gateway:
     server:
       webflux:
         discovery:
           locator:
             enabled: true
             lower-case-service-id: true
         httpclient:
           connect-timeout: 1000
           response-timeout: 10s
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/ # use localhost instead of eurekaserver when running locally
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Jane Bank Gateway Server Application"
    version: "1.0.0"
logging:
  level:
    com:
      jane:
        gatewayserver: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id}%X{span_id}]"
resilience4j.circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
server:
  port: 8072