spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8071/ # use localhost instead of configserver when running locally
server:
  port: 8070
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8070/eureka/ # use localhost instead of eurekaserver when running locally
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id}%X{span_id}]"