spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://configserver:8071/
server:
  port: 8070
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true